### PR TITLE
Remove Model::addFields() method

### PR DESCRIPTION
**Pull request by mvorisek**
and `addField` should probably return Model for chaining, field is named (1st param)...

### CODE REVIEW

**Comment by acicovic** [comment]
@mvorisek what's your reasoning for removing addFields? It does reduce code repetition a lot when you have many fields.

**Comment by mvorisek** [comment]
you can assign complex seed to a variable first if needed

**Comment by acicovic** [comment]
Could  you demonstrate?

**Comment by mvorisek** [comment]
Of course!

```
$this->addFields(['name','address'], ['you must get it now!']);
```
to
```
$seed = ['you must get it now!'];
$this->addField('name', $seed);
$this->addField('address', $seed);
```

**Comment by georgehristov** [comment]
I would not support this change

**Comment by acicovic** [comment]
Personally me neither, but it's up to you guys to decide.

**Comment by DarkSide666** [comment]
No I don't support this.
I see no advantage in removing that method. It only removes existing short-hand functionality.

**Comment by mvorisek** [comment]
not pursuing this for now

**Pull request closed without merging**
