### PR TITLE
Fix phpunit before full upgrade

### PR DESCRIPTION
**Pull request by mvorisek**

### CODE REVIEW

**Comment by mvorisek** [comment]
@DarkSide666 How the install issue? The https://github.com/atk4/schema/pull/50 does not help and you can revert it.

**Comment by DarkSide666** [comment]
https://github.com/atk4/schema/pull/51

**Comment by mvorisek** [comment]
@DarkSide666 But still how to fix it? Seems to be related with https://github.com/atk4/schema/pull/46

**Comment by mvorisek** [comment]
@DarkSide666 ping

**Review by DarkSide666 — APPROVED** [review]
LGTM

**Pull request merged**
