### PR TITLE
Remove NameTrait trait from Model

### PR DESCRIPTION
**Pull request by mvorisek**
It makes almost no sense to have it in Model - why is it there?

Added in https://github.com/atk4/data/commit/c3bd270fadbad7305fa8ca57559b404d45d8cf58 by @romaninsh

### CODE REVIEW

**Review by DarkSide666 — APPROVED** [review]
I think it's not needed. Probably was added for historical reasons when we thought that will store models in persistence object _elements_. Like fields in model. And then we would need model->name.

**Comment by mvorisek** [comment]
Perfect, now `name` is free to be used for standard `name` field/property/hinting. 👍

**Comment by DarkSide666** [comment]
Not really - atk4/ui tests start to fail because of SessionTrait somehow uses these names so I reverted back at least for now.

**Comment by mvorisek** [comment]
Did you checked what the name of object normally is? and if session trait should even be allowed on Model class (I am not againt), but it makes more sense on App/View only or fixing it that way `name` can be used in Models as normal `name` field/property.

**Comment by mvorisek** [comment]
recreated under #596

**Comment by DarkSide666** [comment]
Session trait probably is used in session persistence and probably use model name as a key in session.
Not sure - I didn't check that.

**Comment by mvorisek** [comment]
I will fix it

**Pull request merged**
