### PR TITLE
Model Sequence, lastInserId and other fixes

### PR DESCRIPTION
**Pull request by DarkSide666**
* implement model->sequence
* fix regex to work for uppercase field names too
* lastInsertID should bwe called from Connection and pass model as parameter. This is needed for sequence support because sequence is model/table specific and lastInsertId should know which model/table we have to check.

 - [ ] We probably need to add few sentences in documentation about Model->sequence and Oracle support in general ?

### CODE REVIEW

**Comment by DarkSide666** [comment]
Tests will fail because this PR requires DSQL https://github.com/atk4/dsql/pull/133 first.

**Comment by romaninsh** [comment]
ok, still looks good!

**Comment by romaninsh** [comment]
Imants, i think

https://github.com/atk4/data/blob/develop/src/Reference_SQL_One.php#L44

which is currently `return $m->refLink($this->link)->action('field', [$their_field]);`
should be `return $m->refLink($this->link)->action('field', [$their_field])->reset('order');`

**Comment by romaninsh** [comment]
i approve "even more proper fix" 🗡

**Pull request merged**
