### PR TITLE
Use new Factory methods

### PR DESCRIPTION
**Pull request by mvorisek**
for https://github.com/atk4/core/pull/289

### CODE REVIEW

**Review by georgehristov — APPROVED** [review]
I am still of the opinion we should change the factory method name but this PR is 👍

**Comment by mvorisek** [comment]
@georgehristov to what name?

**Comment by georgehristov** [comment]
`make`, `build`, etc (if we have to avoid `create`)

**Comment by mvorisek** [comment]
we should aim to not use `Xxx:fromSeed()` to support autohinting

**Pull request merged**
