### PR TITLE
WIP Use MySQL 8.0

### PR DESCRIPTION
**Pull request by DarkSide666**
command

https://github.com/atk4/data/runs/534570568

### CODE REVIEW

**Comment by DarkSide666** [comment]
Well, I have no more ideas what else to try to force MySQL 8.0 use old style authentication mechanism.

**Comment by mvorisek** [comment]
@DarkSide666 And do we need the "old style authentication mechanism" at all? I will look at this, but no sooner than in a week, I am very busy now.

**Comment by DarkSide666** [comment]
Ok, thanks!

**Comment by mvorisek** [comment]
@DarkSide666 Solving this seems to be complicated as docker `CMD` can not be specified in Github Action service. I tried to fix it using custom `ENTRYPOINT`, but I was not able to specify even the default file.

The issue seems to be related with https://github.com/atk4/image which uses lighweight Alpine image without the new `caching_sha2_password` plugin support.

**Comment by romaninsh** [comment]
Oh we could include that support there perhaps?

**Comment by mvorisek** [comment]
@romaninsh Yes - the `atk4/image` docker image installs `mysql-client`:
https://github.com/atk4/image/blob/master/Dockerfile#L3
but this client can not be used to interact with the new MySQL 8 as it does not have `caching_sha2_password` support.

Do you have any idea how to fix this without changing the Alpine image to Debian?

**Comment by mvorisek** [comment]
fixed/solved by https://github.com/atk4/data/pull/645

**Pull request closed without merging**
