### PR TITLE
Feature/add action in aftersave hook

### LINKED ISSUE #383: Issue with afterSave, AfterInsert and AfterUpdate Hooks together with hasOne()->addField()
Hi There,

lets hope I can describe this so you understand. I will stick to my real life case.
1) After my model is saved, I want to perform some action. I want to always do this on insert, on update only if certain fields are changed. As I didnt find a way to determine in afterSave hook if its an insert or update operation, the only viable option is to call the action from afterInsert and from afterUpdate hook,

2) The Model has some fields from a hasOne relationship. Like Model->hasOne('tour_type_id')->addFields(['tour_type_name' => 'name', 'activity_id' => 'activity_id']);

3) The action I perform uses one of these fields set by hasOne()->addFields(), and here is the issue:
When I call the action from afterInsert hook, these fields are not populated yet as the reload after save is executed after the afterInsert hook. So my action fails when called from afterInsert hook.

So there is 2 sensible solutions for this situation of which I like the first way more
1) Find a way to determine in afterSave hook if it was an update/insert operation
2) change the order in atk4\data\Model that the afterInsert hook is executed after the reload after save. This could break other stuff as it means a change of logic.

### PR DESCRIPTION
**Pull request by DarkSide666**
Adds `is_update` parameter in `afterSave` hook so we can now know was it insert or update.
fix #383

### CODE REVIEW

**Comment by PhilippGrashoff** [comment]
Hi,

regarding the added docs: in afterUpdate Hook, the model is already reloaded. its done by $to_persistence->update(). So in afterUpdate the model is reloaded, in afterInsert not.

**Comment by PhilippGrashoff** [comment]
And thanks for this PR, will make coding easier :)

**Comment by DarkSide666** [comment]
will fix that in docs. thanks for noticing!

**Comment by PhilippGrashoff** [comment]
Would be a future thing to have afterUpdate and afterInsert hooks the same way :) Now, one has the reloaded model, the other not.

**Comment by DarkSide666** [comment]
Well, that will break backward compatibility because now afterUpdate hook gets data array as parameter, but afterInsert hook gets new id as parameter.

**Comment by PhilippGrashoff** [comment]
Yeah I know, this could be something for V2, to have all hooks behave the same.

**Comment by DarkSide666** [comment]
Rule of thumb I am trying to stick to is to not use before/after Insert/Update hooks but use only before/after Save hooks :)

**Comment by PhilippGrashoff** [comment]
Which is now always possible thanks to this PR ;)

**Pull request merged**
