### PR TITLE
Remove ui property from UserAction

### PR DESCRIPTION
**Pull request by mvorisek**
finish after https://github.com/atk4/ui/pull/1550

### CODE REVIEW

**Comment by mvorisek** [comment]
@ibelar please finish this PR related to the ui PR

I tried to delete all `ui` props from this data repo, but there are quite a lot of uses and I am not sure if all of them can be removed...

**Comment by mvorisek** [comment]
@ibelar these props
image
stay, right?

**Comment by ibelar** [comment]
@mvorisek - I have removed UserAction ui property setting from Model.
I have also delete the $ui property from UserAction Class. Was not sure if we should keep it for backward compatibility or not and mark it as obsolete. If so, please add it back.

**Comment by mvorisek** [comment]
> I have also delete the $ui property from UserAction Class. Was not sure if we should keep it for backward compatibility or not and mark it as obsolete. If so, please add it back.

removing is ok as it will go hand in hand with 2.4 ui rel

please approve/merge this PR, the changes are from you, but I am the initiating author and can not merge it...

**Review by ibelar — APPROVED** [review]
LGTM

**Pull request merged**
