### PR TITLE
Xxx::addFields() input must use key for name

### PR DESCRIPTION
**Pull request by mvorisek**
still not sure if `addFields` methods should be presented or not, but they will stay at least for v4.0 - related PR https://github.com/atk4/data/pull/990

### CODE REVIEW

**Comment by mvorisek** [comment]
@mkrecek234 AFAK you use and was defending `addFields` method, it stays, wdyt about this change, do you support the consistency?

**Comment by mkrecek234** [comment]
> @mkrecek234 AFAK you use and was defending `addFields` method, it stays, wdyt about this change, do you support the consistency?

I dislike the ['name' => [], 'company' => []] - we want to still ensure that Atk4 remains agile in the sense that with few lines of code you can have a working prototype. So we should keep: addFields(['name', 'company', ... ]) functionality without the need to configure it.

**Comment by mvorisek** [comment]
the original input is problematic, as it does too much transformations to allow us to describe the type for phpstan

also, for SQL HasOne, it allowed the their field to be specified as the 0 => value, but this is breaking seed definition, this key is reserved for the seed class name

**Comment by mvorisek** [comment]
Maybe someday, thank you @mkrecek234 for the feedback.

**Pull request closed without merging**
