### PR TITLE
Fix logic error in example

### PR DESCRIPTION
**Pull request by PhilippGrashoff**
Checking if field value is unique: The condition has to be that the id of the new Instance IS NOT the id of the original record.

### CODE REVIEW

**Comment by PhilippGrashoff** [comment]
Ah forget it I took client_id for id_field...

**Comment by DarkSide666** [comment]
but `    ->addCondition($m->id_field, '!=', $m->id)   // has another order` should be there.
can you change your PR and add that line instead and i will merge in.

**Comment by DarkSide666** [comment]
@romaninsh why not? I think we just need to change that one line there from client_id check to id and that's all. Don't you think so?

**Comment by romaninsh** [comment]
i think the text explaining example was a bit too brief. Was unclear to me what i wrote myself 😄. probably need to better explain case and how it's solved.

**Pull request merged**
