### PR TITLE
Lokalise: Translations update

### PR DESCRIPTION
**Pull request by romaninsh**
This pull request was initiated by Lokalise (user Romans Malinovskis) at 2019-09-19 21:09:15

### CODE REVIEW

**Review by abbadon1334 — COMMENTED** [review]
format is ok, but i think separate the translations with namespace or define a global namespace like `atk` like in the first version is better.

**Comment by romaninsh** [comment]
@abbadon1334 i'm not sure how to configure lokalize like that. It simply outputs everything into a file, if it's just variables, it has no namespace.

**Comment by romaninsh** [comment]
@abbadon1334  - check invite to https://lokalise.com/project/777597515d820a1f5c9351.76644895/

**Comment by DarkSide666** [comment]
Cool project. But some namespaces would be good to have. Especially for larger projects.

**Review by DarkSide666 — APPROVED** [review]

**Comment by abbadon1334** [comment]
ok! i have just take a look, @romaninsh correct me if i'm wrong.
- you want to create a project for every package
- for every package we will have a folder `locale` with translations

if we add somewhere TranslatableTrait and call `_($string)` :
 - if there is no App -> it will return $string
 - if there is App -> it will call App->_($string) -> ???

??? we have to create a Translator or something that load one time the language files to process the $string and return $translated_string

How we can load them?
i just checked composer to see if can be done something like mapping with include with no luck 

If we add a class for every package with something like this : 

```php
namespace atk4\data;

class Locale {

    use atk4\core\ConfigTrait {
        readConfig as protected;
        getConfig as protected;
        setConfig as protected;
    }

    public function load(string $locale, bool $force_reload = true, string $path = __DIR__ . '/../locale/')
    {
        if (empty($this->config) || $force_reload) {
            $this->getConfig($path . $locale);
        }

        return $this->config;
    }
}
```

this way we always have the correct path for default translations and we can merge them in app or in an external translator.

Just write while i'm thinking.

What you think?

**Comment by romaninsh** [comment]
@abbadon1334 yes you are correct. For loading the class - i'm not sure how to find it - but here are 2 options:

1. when setting translatable trait - we can also specify name of the file to include.
2. we can use namespaces and wrap strings into a class, load the class from composer. We could recommend lokalize to implement new PHP export format we just need to explain the benefits and what  problem it would solve.

**Review by abbadon1334 — APPROVED** [review]

**Pull request closed without merging**
