### PR TITLE
Update hintable dep to 1.2.x

### PR DESCRIPTION
**Pull request by mvorisek**
now we also allow only `1.2.*` instead of `1.*`

### CODE REVIEW

**Review by georgehristov — APPROVED** [review]
LGTM

**Comment by mvorisek** [comment]
@georgehristov any idea how to fix https://github.com/mvorisek/atk4-hintable-mirror/blob/develop/tests/Data/HintableModelTest.php#L102 ? (related with references and scopes)

currently it requires persistence set before ref() can be even returned

**Comment by georgehristov** [comment]
> @ghristov#5652 any idea how to fix https://github.com/mvorisek/atk4-hintable-mirror/blob/develop/tests/Data/HintableModelTest.php#L102 ? (related with references and scopes)
>
> currently it requires persistence set before ref() can be even returned

@mvorisek you referenced somebody else :)

Anyway I will have a look

**Comment by mvorisek** [comment]
@georgehristov did you find a solution?

update: link with fixed version/commit is: https://github.com/mvorisek/atk4-hintable-mirror/blob/1.2.1/tests/Data/HintableModelTest.php#L100

**Pull request merged**
