### PR TITLE
Fix CS to PSR-12

### PR DESCRIPTION
**Pull request by mvorisek**
Add CS config and fix PSR-12 errors.

### CODE REVIEW

**Review by abbadon1334 — APPROVED** [review]
LGTM, nice work. We need to resolve few conflicts and format all code to follow this.
@DarkSide666 @romaninsh We can switch rules even on the other repos.

**Comment by mvorisek** [comment]
@romaninsh offered to fix this in https://github.com/atk4/ui/pull/980 I expect him to do so for at least for core, data, ui, dql repos.

DO NOT MERGE THIS PR

**Comment by mvorisek** [comment]
@romaninsh can you setup StyleCI for this repo like for `atk4/core` or `atk4/ui`? Ie. to add spaces beside string concat operator, `=>` etc.? Thanks.

**Comment by romaninsh** [comment]
@mvorisek Will do mate! Lets get everthyyyngi merged first then.

**Pull request closed without merging**
