### PR TITLE
use property to define field seed properties

### PR DESCRIPTION
**Pull request by georgehristov**
- use single generic `Field::getSeed` method that checks seed properties for each field type
- use class constant for field type mapping
- minor changes in `Numeric` field property names for simplification
- backward compatible use of `$fx` property in `Callback` field instead of `$expr`
- add field tests

### CODE REVIEW

**Comment by romaninsh** [comment]
is this up-to-date? could you merge develop in?

**Comment by romaninsh** [comment]
OH i see you PR this into /number-field

**Comment by DarkSide666** [comment]
I wonder if number-field branch is at all needed.... not sure what it was.

**Comment by georgehristov** [comment]
It is separating the field logic in dedicated classes and I believe it is necessary.
I built on the direction of this branch and created a PR for review and consideration.

**Comment by georgehristov** [comment]
Reference https://github.com/atk4/data/wiki/ADP1904---Typecasting-and-serialization-cleanup

**Pull request merged**
